//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverApp.Log {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj", ConfigurationName="Log.LogSoap")]
    public interface LogSoap {
        
        // CODEGEN: Generating message contract since element name startDayResult from namespace http://cms.gre.ac.uk/pdc/jjj is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/startDay", ReplyAction="*")]
        DriverApp.Log.startDayResponse startDay(DriverApp.Log.startDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/startDay", ReplyAction="*")]
        System.Threading.Tasks.Task<DriverApp.Log.startDayResponse> startDayAsync(DriverApp.Log.startDayRequest request);
        
        // CODEGEN: Generating message contract since element name endDayResult from namespace http://cms.gre.ac.uk/pdc/jjj is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/endDay", ReplyAction="*")]
        DriverApp.Log.endDayResponse endDay(DriverApp.Log.endDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/endDay", ReplyAction="*")]
        System.Threading.Tasks.Task<DriverApp.Log.endDayResponse> endDayAsync(DriverApp.Log.endDayRequest request);
        
        // CODEGEN: Generating message contract since element name startJourneyResult from namespace http://cms.gre.ac.uk/pdc/jjj is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/startJourney", ReplyAction="*")]
        DriverApp.Log.startJourneyResponse startJourney(DriverApp.Log.startJourneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/startJourney", ReplyAction="*")]
        System.Threading.Tasks.Task<DriverApp.Log.startJourneyResponse> startJourneyAsync(DriverApp.Log.startJourneyRequest request);
        
        // CODEGEN: Generating message contract since element name endJourneyResult from namespace http://cms.gre.ac.uk/pdc/jjj is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/endJourney", ReplyAction="*")]
        DriverApp.Log.endJourneyResponse endJourney(DriverApp.Log.endJourneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cms.gre.ac.uk/pdc/jjj/endJourney", ReplyAction="*")]
        System.Threading.Tasks.Task<DriverApp.Log.endJourneyResponse> endJourneyAsync(DriverApp.Log.endJourneyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class startDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="startDay", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.startDayRequestBody Body;
        
        public startDayRequest() {
        }
        
        public startDayRequest(DriverApp.Log.startDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class startDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public startDayRequestBody() {
        }
        
        public startDayRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class startDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="startDayResponse", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.startDayResponseBody Body;
        
        public startDayResponse() {
        }
        
        public startDayResponse(DriverApp.Log.startDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class startDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startDayResult;
        
        public startDayResponseBody() {
        }
        
        public startDayResponseBody(string startDayResult) {
            this.startDayResult = startDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="endDay", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.endDayRequestBody Body;
        
        public endDayRequest() {
        }
        
        public endDayRequest(DriverApp.Log.endDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class endDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public endDayRequestBody() {
        }
        
        public endDayRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="endDayResponse", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.endDayResponseBody Body;
        
        public endDayResponse() {
        }
        
        public endDayResponse(DriverApp.Log.endDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class endDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string endDayResult;
        
        public endDayResponseBody() {
        }
        
        public endDayResponseBody(string endDayResult) {
            this.endDayResult = endDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class startJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="startJourney", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.startJourneyRequestBody Body;
        
        public startJourneyRequest() {
        }
        
        public startJourneyRequest(DriverApp.Log.startJourneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class startJourneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public startJourneyRequestBody() {
        }
        
        public startJourneyRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class startJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="startJourneyResponse", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.startJourneyResponseBody Body;
        
        public startJourneyResponse() {
        }
        
        public startJourneyResponse(DriverApp.Log.startJourneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class startJourneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string startJourneyResult;
        
        public startJourneyResponseBody() {
        }
        
        public startJourneyResponseBody(string startJourneyResult) {
            this.startJourneyResult = startJourneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="endJourney", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.endJourneyRequestBody Body;
        
        public endJourneyRequest() {
        }
        
        public endJourneyRequest(DriverApp.Log.endJourneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class endJourneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public endJourneyRequestBody() {
        }
        
        public endJourneyRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="endJourneyResponse", Namespace="http://cms.gre.ac.uk/pdc/jjj", Order=0)]
        public DriverApp.Log.endJourneyResponseBody Body;
        
        public endJourneyResponse() {
        }
        
        public endJourneyResponse(DriverApp.Log.endJourneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cms.gre.ac.uk/pdc/jjj")]
    public partial class endJourneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string endJourneyResult;
        
        public endJourneyResponseBody() {
        }
        
        public endJourneyResponseBody(string endJourneyResult) {
            this.endJourneyResult = endJourneyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogSoapChannel : DriverApp.Log.LogSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogSoapClient : System.ServiceModel.ClientBase<DriverApp.Log.LogSoap>, DriverApp.Log.LogSoap {
        
        public LogSoapClient() {
        }
        
        public LogSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DriverApp.Log.startDayResponse DriverApp.Log.LogSoap.startDay(DriverApp.Log.startDayRequest request) {
            return base.Channel.startDay(request);
        }
        
        public string startDay(int id) {
            DriverApp.Log.startDayRequest inValue = new DriverApp.Log.startDayRequest();
            inValue.Body = new DriverApp.Log.startDayRequestBody();
            inValue.Body.id = id;
            DriverApp.Log.startDayResponse retVal = ((DriverApp.Log.LogSoap)(this)).startDay(inValue);
            return retVal.Body.startDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DriverApp.Log.startDayResponse> DriverApp.Log.LogSoap.startDayAsync(DriverApp.Log.startDayRequest request) {
            return base.Channel.startDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<DriverApp.Log.startDayResponse> startDayAsync(int id) {
            DriverApp.Log.startDayRequest inValue = new DriverApp.Log.startDayRequest();
            inValue.Body = new DriverApp.Log.startDayRequestBody();
            inValue.Body.id = id;
            return ((DriverApp.Log.LogSoap)(this)).startDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DriverApp.Log.endDayResponse DriverApp.Log.LogSoap.endDay(DriverApp.Log.endDayRequest request) {
            return base.Channel.endDay(request);
        }
        
        public string endDay(int id) {
            DriverApp.Log.endDayRequest inValue = new DriverApp.Log.endDayRequest();
            inValue.Body = new DriverApp.Log.endDayRequestBody();
            inValue.Body.id = id;
            DriverApp.Log.endDayResponse retVal = ((DriverApp.Log.LogSoap)(this)).endDay(inValue);
            return retVal.Body.endDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DriverApp.Log.endDayResponse> DriverApp.Log.LogSoap.endDayAsync(DriverApp.Log.endDayRequest request) {
            return base.Channel.endDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<DriverApp.Log.endDayResponse> endDayAsync(int id) {
            DriverApp.Log.endDayRequest inValue = new DriverApp.Log.endDayRequest();
            inValue.Body = new DriverApp.Log.endDayRequestBody();
            inValue.Body.id = id;
            return ((DriverApp.Log.LogSoap)(this)).endDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DriverApp.Log.startJourneyResponse DriverApp.Log.LogSoap.startJourney(DriverApp.Log.startJourneyRequest request) {
            return base.Channel.startJourney(request);
        }
        
        public string startJourney(int id) {
            DriverApp.Log.startJourneyRequest inValue = new DriverApp.Log.startJourneyRequest();
            inValue.Body = new DriverApp.Log.startJourneyRequestBody();
            inValue.Body.id = id;
            DriverApp.Log.startJourneyResponse retVal = ((DriverApp.Log.LogSoap)(this)).startJourney(inValue);
            return retVal.Body.startJourneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DriverApp.Log.startJourneyResponse> DriverApp.Log.LogSoap.startJourneyAsync(DriverApp.Log.startJourneyRequest request) {
            return base.Channel.startJourneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DriverApp.Log.startJourneyResponse> startJourneyAsync(int id) {
            DriverApp.Log.startJourneyRequest inValue = new DriverApp.Log.startJourneyRequest();
            inValue.Body = new DriverApp.Log.startJourneyRequestBody();
            inValue.Body.id = id;
            return ((DriverApp.Log.LogSoap)(this)).startJourneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DriverApp.Log.endJourneyResponse DriverApp.Log.LogSoap.endJourney(DriverApp.Log.endJourneyRequest request) {
            return base.Channel.endJourney(request);
        }
        
        public string endJourney(int id) {
            DriverApp.Log.endJourneyRequest inValue = new DriverApp.Log.endJourneyRequest();
            inValue.Body = new DriverApp.Log.endJourneyRequestBody();
            inValue.Body.id = id;
            DriverApp.Log.endJourneyResponse retVal = ((DriverApp.Log.LogSoap)(this)).endJourney(inValue);
            return retVal.Body.endJourneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DriverApp.Log.endJourneyResponse> DriverApp.Log.LogSoap.endJourneyAsync(DriverApp.Log.endJourneyRequest request) {
            return base.Channel.endJourneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DriverApp.Log.endJourneyResponse> endJourneyAsync(int id) {
            DriverApp.Log.endJourneyRequest inValue = new DriverApp.Log.endJourneyRequest();
            inValue.Body = new DriverApp.Log.endJourneyRequestBody();
            inValue.Body.id = id;
            return ((DriverApp.Log.LogSoap)(this)).endJourneyAsync(inValue);
        }
    }
}
